#!/usr/bin/env sh
# YES_ZSH

bak() {
    [ $# -gt 0 ] || { printf "%s\n" "$0: too few arguments" >&2; return 1; }
    local ret=0
    for f; do
        if [ -s "$f.bak" ]; then
            bak "$f.bak" || ret=1
        fi
        cp -p "$f" "$f.bak"
    done
    return $ret
}

[ "${SOURCING:-0}" -gt 0 ] || bak "$@"
