#!/usr/bin/env bash
# YES_ZSH
# YES_BASH
# NO_DASH

colors() { ### @-
    ### display all combinations of foreground and background terminal colors.
    ### this only includes the basic 16-color palette.
    ### excluding boilerplate, this script is a mere a 76-characters long!
    ###
    ### ![terminal colors](https://eaguru.guru/t/terminal-colors.png)
    [ $# -eq 0 ] || { printf "%s\n" "$0: does not take arguments" >&2; return 1; }
    printf "\e[%dm$(printf " \e[%dm mV \e[40m" {4,10}{0..7})\e[0m\n" {3,9}{0..7}
}

[ "${SOURCING:-0}" -gt 0 ] || colors "$@"
