#!/usr/bin/env sh
# YES_ZSH

countdiff() {
    [ $# -le 2 ] || { printf "%s\n" "$0: too many arguments" >&2; return 1; }
    git --no-pager diff --stat --no-color --no-index "$1" "$2" \
    | awk '/changed/{print $4+$6;a=1}END{if(!a)print 0}'
}

[ "${SOURCING:-0}" -gt 0 ] || countdiff "$@"
