#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

dated() {
    local ts= u=0
    [ "$1" != -u ] || { shift; u=1; }
    if [ $# = 0 ]; then
        # -u doesn't actually do anything here, but...
        if [ $u = 1 ]; then date -u '+%s'; else date '+%s'; fi
    fi
    for ts; do
        if [ $u = 1 ]; then date -u -d '@'"$ts"; else date -d '@'"$ts"; fi
    done
}

[ -n "${preload+-}" ] || dated "$@"
