#!/usr/bin/env sh
# compat: +ash +bash +dash +zsh

days() { ### @-
    ### compute the number of days since a given date.
    ###
    ### ```
    ### $ days 'January 1 1970'
    ### 18838
    ### ```
    [ $# -le 1 ] || { printf "%s\n" "$0: too many arguments" >&2; return 1; }
    echo $(( ($(date +%s) - $(date -d "$1" +%s)) / 60 / 60 / 24 ))
}

[ -n "${preload+-}" ] || days "$@"
