#!/usr/bin/env bash
# YES_ZSH

days() {
    [ $# -le 1 ] || { printf "%s\n" "$0: too many arguments" >&2; return 1; }
    echo $(( ($(date +%s) - $(date -d "$1" +%s)) / 60 / 60 / 24 ))
}

[ "${SOURCING:-0}" -gt 0 ] || days "$@"
