#!/usr/bin/env zsh
# YES_ZSH
# NO_BASH
# NO_DASH

dbusiest() {
    [ $# -le 0 ] || { printf "%s\n" "$0: too many arguments" >&2; return 1; }
    local c d
    for d in *(FDN); do
        print $(find $d 2>/dev/null | wc -l) $d
    done | sort -nr | while read c d; do
        echo -E $c $d
    done
    [ -z $d ] && return 1
}

[ "${SOURCING:-0}" -gt 0 ] || dbusiest
