#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

echo2() { ### @-
    ### print arguments joined by spaces to stderr without parsing anything.
    ###
    ### ```
    ### $ echo -e 'this\nthat' those
    ### this
    ### that those
    ### $ echo2 -e 'this\nthat' those
    ### -e this\nthat those
    ### ```
    local IFS=' '
    printf "%s\n" "$*" >&2
}

[ -n "${preload+-}" ] || echo2 "$@"
