#!/usr/bin/env sh
# compat: +ash +bash +dash +hush -ksh +mksh +oksh +osh +posh +yash +zsh

echo2() { ### @-
    ### print arguments joined by spaces to stderr without parsing anything.
    ###
    ### ```
    ### $ echo -e 'this\nthat' those
    ### this
    ### that those
    ### $ echo2 -e 'this\nthat' those
    ### -e this\nthat those
    ### ```
    local IFS=' '
    printf '%s\n' "$*" >&2
}

[ -n "${preload+-}" ] || echo2 "$@"
