#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

explore() { ### @- open a single directory in `explorer.exe`, defaulting to `$PWD`.
    [ -n "$MSYSTEM" ] || { printf "%s\n" "$0: only for MSYS2" >&2; return 1; }
    [ $# -le 1 ] || { printf "%s\n" "$0: too many arguments" >&2; return 1; }
    explorer "$(cygpath -w "${1:-.}")"
}

[ "${SOURCING:-0}" -gt 0 ] || explore "$@"
