#!/usr/bin/env sh
# compat: +ash +bash +dash +zsh

explore() { ### @- open a single directory in `explorer.exe`, defaulting to `$PWD`.
    [ -n "$MSYSTEM" ] || { printf '%s\n' "$0: only for MSYS2" >&2; return 1; }
    [ $# -le 1 ] || { printf '%s\n' "$0: too many arguments" >&2; return 1; }
    explorer "$(cygpath -w "${1:-.}")"
}

[ -n "${preload+-}" ] || explore "$@"
