#!/usr/bin/env zsh
# ghmd - format GitHub markdown
# via: https://leahneukirchen.org/dotfiles/.zshrc
# example: ghmd < README.md > README.html
# YES_ZSH
# YES_BASH
# YES_DASH

ghmd() { ### @-
    ### convert a markdown file to HTML in the style of GitHub.
    ### note that this uses GitHub's API, so it requires internet connectivity.
    ###
    ### this script utilizes the CSS provided at
    ### [sindresorhus/github-markdown-css.](https://github.com/sindresorhus/github-markdown-css)
    printf '%s' '<!DOCTYPE html><html><head><meta charset="utf-8"><link ' \
      'href="https://eaguru.guru/t/github-markdown.css" ' \
      'media="all" rel="stylesheet" type="text/css"/></head><body ' \
      'style="box-sizing: border-box; min-width: 200px; max-width: 980px; ' \
      'margin: 0 auto; padding: 45px;"><article class="markdown-body">'
    curl -s --data-binary @- -H 'Content-Type: text/plain' \
      https://api.github.com/markdown/raw
    local ret=$?
    printf '%s' '</article></body></html>'
    return $ret
}

[ "${SOURCING:-0}" -gt 0 ] || ghmd "$@"
