#!/usr/bin/env sh
# YES_ZSH YES_BASH YES_DASH YES_ASH

grop4() { ### @- [`grop`](#grop) for IPv4s.
    grep -oP -- '(?<=^|[^\d.])((0|1\d\d|2[0-4]\d|25[0-5]|[1-9]\d?)\.((?2))\.((?2))\.((?2)))(?=$|[^\d.])'
}

[ -n "${preload+-}" ] || grop4 "$@"
