#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

has() { ### @-
    ### print the result of `which` if the program is found, else simply return 1.
    ###
    ### ```
    ### export CC="$(has clang || has clang-3.8 || has gcc)"
    ### ```
    if [ -n "$ZSH_VERSION" ]; then
        whence -p "$1"
    else
        which "$1" >/dev/null 2>&1 && which "$1"
    fi
}

[ "${SOURCING:-0}" -gt 0 ] || has "$@"
