#!/usr/bin/env sh
# compat: +ash +bash +dash +zsh

has() { ### @- [`have`,](#have) silently.
    if [ -z "$ZSH_VERSION" ]; then which -- "$1"; else whence -p -- "$1"; fi
} >/dev/null 2>/dev/null

[ -n "${preload+-}" ] || has "$@"
