#!/usr/bin/env sh
# compat: +ash +bash +dash +hush +ksh +mksh +oksh +osh +posh +yash +zsh

have() { ### @- print the result of `which` if the program is found, else simply return 1.
    ### ```
    ### export SOLVER="$(have kissat || have picosat || have cadical || have minisat)"
    ### ```
    has "$@" && printf %s\\n "$REPLY"
}

[ -n "${preload+-}" ] || . ~/sh/preload || exit 2
eval ${preload:-preload} has
[ -n "${preload+-}" ] || have "$@"
