#!/usr/bin/env sh
# compat: +ash +bash +dash +hush +ksh +mksh +oksh +osh +posh +yash +zsh

entrypoint() {
    depends has
    execute have "$@"
}

have() { ### @- print the result of `which` if the program is found, else simply return 1.
    ### ```
    ### export SOLVER="$(have kissat || have picosat || have cadical || have minisat)"
    ### ```
    has "$@" && printf %s\\n "$REPLY"
}

${preload+:} . ~/sh/bootstrap
