#!/usr/bin/env zsh
# YES_ZSH
# YES_BASH
# YES_DASH

# though technically compatible with other shells,
# extra functionality is through zsh's extended arithmetic functions.

hex() {
    printf "%08X\n" "$(($@))"
}

[ "${SOURCING:-0}" -gt 0 ] || hex "$@"
