#!/usr/bin/env sh
# compat: +ash +bash +dash +zsh

join2() { ### @- join every other line.
    # TODO: argc, also better interface that allows n file inputs without stdin.
    paste -d" " - -
}

[ -n "${preload+-}" ] || join2 "$@"
