#!/bin/zsh
monitor() {
    local time=$1
    local cmd=$2
    local stop=0
    trap stop=1 INT
    echo -en "\e[H\e[2J"
    while [ $stop -eq 0 ]; do
        echo -en "\e[1J\e[H"
        $cmd 2>&1 | fold -w $COLUMNS | tail -$((LINES-1))
        sleep $time || break
    done
}
monitor $1 $2
