#!/usr/bin/env bash
# YES_ZSH
# YES_BASH
# NO_DASH
# NO_ASH

morecolors() { ### @- print all 256 colors that are available on most terminals.
    # borrowed from leah2's dotfiles.
    local i=
    for i in {0..255}; do
        printf '\e[48;5;%dm\e[38;5;15m %03d ' $i $i
        printf '\e[33;5;0m\e[38;5;%dm %03d ' $i $i
        [ "$(( i+1 <= 16 ? (i+1) %  8 : ( (i+1)-16) %  6 ))" = 0 ] && printf '\e[0m\n'
        [ "$(( i+1 <= 16 ? (i+1) % 16 : ( (i+1)-16) % 36 ))" = 0 ] && printf '\e[0m\n'
    done
}

[ -n "${preload+-}" ] || morecolors "$@"
