#!/usr/bin/env sh
# compat: +ash +bash +dash +hush -ksh +mksh +oksh +osh +posh +yash +zsh

note() { ### @-
    ### act like [`echo2`,](#echo2) but use a bright color to stand out more.
    ###
    ### **NOTE:** there also exists a [note(1)](https://www.daemon.de/projects/note/)
    ### program provided by the *note* package that i don't use.
    local IFS=" "
    printf '\033[1m%s\033[0m\n' "$*" >&2
}

[ -n "${preload+-}" ] || note "$@"
