#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

pacbm() { ### @-
    ### display and order installed pacman packages by their filesize ascending,
    ### and their sum. requires `expac`.
    ###
    ### ```
    ### $ pacbm | head -n -1 | tail -2
    ###   204.78M clang
    ###   235.44M linux-firmware
    ### ```
    expac -s '%m %n' | awk '
    {t+=$1;printf("%8.2fM %s\n",$1/(1024*1024),$2)}
    END{printf("%8.2fM\n",t/(1024*1024))}
    ' | sort -n
}

[ "${SOURCING:-0}" -gt 0 ] || pacbm "$@"
