#!/usr/bin/env sh
# YES_ZSH

pacbm() {
    expac -s '%m %n' | awk '
    {t+=$1;printf("%8.2fM %s\n",$1/(1024*1024),$2)}
    END{printf("%8.2fM\n",t/(1024*1024))}
    ' | sort -n
}

[ "${SOURCING:-0}" -gt 0 ] || pacbm "$@"
