#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

# TODO: source pippy here? this may affect dash compatibility.

pegg() {
    [ $# -ge 2 ] || { printf "%s\n" "$0: too few arguments" >&2; return 1; }
    pippy "https://github.com/$1/$2/tarball/${3:-master}#egg=$2"
}

[ "${SOURCING:-0}" -gt 0 ] || pegg "$@"
