#!/usr/bin/env sh
# compat: +ash +bash +dash -hush +zsh

pippy() { ### @-
    ### install Python packages using pip,
    ### but only update their dependencies as required.
    ### this uses [`maybesudo`](#maybesudo) internally.
    if [ -s ~/work/automamba ]; then
        ~/work/automamba --pip install --upgrade --upgrade-strategy only-if-needed --dry-run "$@"
        confirm || return
        ~/work/automamba --pip install --upgrade --upgrade-strategy only-if-needed "$@"
        return
    fi
    maybesudo python3 -m pip install --upgrade --upgrade-strategy only-if-needed "$@"
}

[ -n "${preload+-}" ] || . ~/sh/preload || exit 2
eval ${preload:-preload} has maybesudo confirm
[ -n "${preload+-}" ] || pippy "$@"
