#!/usr/bin/env sh
# compat: +ash +bash +dash +hush +ksh +mksh +oksh +osh +posh +yash +zsh

pre() { ### @-
    ### dump all the `#define`s that `$CC $CPPFLAGS $CFLAGS $LDFLAGS` would result in.
    ###
    ### ```
    ### $ pre | grep char
    ### #define __UINT_LEAST8_TYPE__ unsigned char
    ### #define __UINT8_TYPE__ unsigned char
    ### #define __INT8_TYPE__ signed char
    ### #define __INT_LEAST8_TYPE__ signed char
    ### #define __INT_FAST8_TYPE__ signed char
    ### #define __UINT_FAST8_TYPE__ unsigned char
    ### ```
    [ -z "$ZSH_SUBSHELL" ] || setopt local_options sh_word_split
    ${CC:-gcc} -dM -E - ${CPPFLAGS-} ${CFLAGS-} ${LDFLAGS-} < /dev/null
}

[ -n "${preload+-}" ] || pre "$@"
