#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

psbm() { ### @-
    [ -z "$MSYSTEM" ] || { printf "%s\n" "$0: unsupported on MSYS2" >&2; return 1; }
    ps axco rss,pid,command | awk '
    NR>1&&$1>0{t+=$1;printf("%8.2fM %7d %s\n",$1/1024,$2,$3)}
    END{printf("%8.2fM\n",t/1024)}
    ' | sort -n
}

[ "${SOURCING:-0}" -gt 0 ] || psbm "$@"
