#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

randir() {
    find -maxdepth 1 -type d \( -path '/root' -prune -o -print \) | tail -n+2 | shuf | head -n1
}

[ "${SOURCING:-0}" -gt 0 ] || randir "$@"
