#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

# works with busybox.

randir() { ### @-
    ### display a random directory in the current working directory.
    ###
    ### ```
    ### $ randir
    ### ./sh
    ### ```
    find -maxdepth 1 -type d \( -path '/root' -prune -o -print \) | tail -n+2 | shuf | head -n1
}

[ -n "${preload+-}" ] || randir "$@"
