#!/usr/bin/env sh
# compat: +ash +bash +dash +zsh

# works with busybox tr.

rot13() { ### @-
    ### rot13 with numbers rotated as well.
    ###
    ### ```
    ### $ rot13 <<< abc123
    ### nop678
    ### ```
    ###
    ### **NOTE:** there also exists rot13(1) programs provided by
    ### the *bsdgames* and *hxtools* packages that i don't use.
    tr -- A-Za-z0-9 N-ZA-Mn-za-m5-90-4
}

[ -n "${preload+-}" ] || rot13 "$@"
