#!/usr/bin/env bash
# YES_ZSH

scramble() {
    local eggs='s/@\(\w\)\(\w\)\(\w\)/@\3\1@\2/g'
    sed \
    -e 's/\b\w/&@/g' \
    -e "$eggs" -e "$eggs" -e "$eggs" -e "$eggs" \
    -e "$eggs" -e "$eggs" -e "$eggs" -e "$eggs" \
    -e 's/@//g'
}

[ "${SOURCING:-0}" -gt 0 ] || scramble "$@"
