#!/usr/bin/env bash
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

scropt() { ### @-
    ### run `scrot` through `optipng` and save the result to `~/play/$(now).png`.
    ###
    ### ```
    ### $ ~/sh/sc $(~/sh/scropt -s -d0.5)
    ### ```
    local now= fn=
    now="$(now)" || return
    fn="$HOME/play/$now.png"
    scrot "$fn" -e 'optipng -quiet $f' "$@" && echo "$fn"
}

[ -n "${preload+-}" ] || . ~/sh/preload || exit 2
eval ${preload:-preload} now
[ -n "${preload+-}" ] || scropt "$@"
