#!/usr/bin/env bash
# YES_ZSH

scropt() { ### @-
    ### run `scrot` through `optipng` and save the result to `~/play/$(now).png`.
    ###
    ### ```
    ### $ ~/sh/sc $(~/sh/scropt -s -d0.5)
    ### ```
    local now=$(now)
    [ $? -eq 0 ] || return $?
    local fn="$HOME/play/$now.png"
    scrot "$fn" -e "optipng -quiet \$f" "$@"
    [ $? -eq 0 ] && echo "$fn" || return $?
}

[ -n "${preload+-}" ] || . ~/sh/preload || exit 2
eval ${preload:-preload} now
[ -n "${preload+-}" ] || scropt "$@"
