#!/usr/bin/env dash
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

# works with busybox ash.

slitt() { ### @-
    ### view specific columns of text.
    ### this version of `slit` uses tabs for its field separators.
    [ $# -gt 0 ] || { printf "%s\n" "$0: too few arguments" >&2; return 1; }
    #echo "$@" | awk '{for(i=1;i<NF;i++)printf"$%s,",$(i);print"$"$NF}'
    local fields="$(printf ',$%s' $@ | cut -b2-)"
    awk "BEGIN { FS=\"\\t\"; OFS=\"\\t\" } { print $fields }"

    # via: https://github.com/sorin-ionescu/prezto/
    #awk "BEGIN { FS=\"\\t\"; OFS=\"\\t\" } { print ${(j:,:):-\$${^@}} }"
}

[ -n "${preload+-}" ] || slitt "$@"
