#!/usr/bin/env zsh
# via: https://github.com/sorin-ionescu/prezto/
# this version uses tabs for input/output field separators.
# YES_ZSH

slitt() {
    awk "BEGIN { FS=\"\\t\"; OFS=\"\\t\" } { print ${(j:,:):-\$${^@}} }"
}

[ "${SOURCING:-0}" -gt 0 ] || slitt "$@"
