#!/usr/bin/sh
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

sortip() { ### @- sort lines numerically by IPv4 segments.
    sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n "$@"
}

[ -n "${preload+-}" ] || sortip "$@"
