#!/usr/bin/env sh
# compat: +ash +bash +dash +zsh

entrypoint() {
    depends argc echo2 note
    execute stfu "$@"
}

stfu() { ### @-
    ### invoke a command, silencing stdout and stderr *unless* the command fails.
    ###
    ### **NOTE:** don't use `stfu` for handling sensitive data or commands!
    ### use it for 7zip.
    ###
    ### note that the tail commands in the example below are from `stfu` itself;
    ### they are echoed to reveal the temp paths for any further investigation.
    ###
    ### ```
    ### $ touch butts
    ### $ STFU_TAIL=5
    ### $ stfu 7z a butts.7z butts
    ### $ stfu 7z a butts.7z asses
    ### command failed with exit status 1:
    ### 7z a butts.7z asses
    ###
    ### $ tail -n 5 /tmp/stfu.CoJ0vmJsqA/out_1627942118
    ### Scan WARNINGS for files and folders:
    ###
    ### asses : The system cannot find the file specified.
    ### ----------------
    ### Scan WARNINGS: 1
    ###
    ### $ tail -n 5 /tmp/stfu.CoJ0vmJsqA/err_1627942118
    ###
    ### WARNING: The system cannot find the file specified.
    ### asses
    ###
    ###
    ### ```
    argc $# -ge 1 "$0" || return
    local dirty= err= out= perms= realtemp= ret= tail= temp= time=

    dirty=0 temp="${STFU_DIR-}"
    if [ -z "${temp:++}" ]; then
        temp="$(exec mktemp -dt stfu.XXXXXXXXXX)" ||
        { printf >&2 %s\\n "$0: failed create temporary directory"; return 1; }
        dirty=1
    fi

    # NOTE: this stat command will not work on BSD-likes,
    #       but it will work with GNU coreutils and busybox.
    perms="$(exec stat -c %a -- "$temp")"
    realtemp="$(exec readlink -f -- "$temp")"
    [ -x /msys2.exe ] && perms=700 # MSYS2 is insecure, oh well.

    if [ -d "$temp" ] && [ "$realtemp" = "$temp" ] && [ "$perms" = 700 ]; then
        if [ $dirty -ne 0 ]; then
            export STFU_DIR="$temp"
        fi
    else
        if [ -n "$STFU_DIR" ]; then
            printf >&2 %s\\n "$0: invalid temporary directory, please unset STFU_DIR"
        else
            printf >&2 %s\\n "$0: something went horribly wrong, maybe you can tell?" "$perms" "$realtemp"
        fi
        return 1
    fi

    time="$(exec date +%s)" ||
    { printf >&2 %s\\n "$0: failed to get current time"; return 1; }

    mkdir -p "$temp" ||
    { printf >&2 %s\\n "$0: failed to create temp directory"; return 1; }

    while [ -e "$temp/out_$time" ] || [ -e "$temp/err_$time" ]; do time=$((time+1)); done
    out="$temp/out_$time"
    err="$temp/err_$time"

    touch -- "$out" "$err" ||
    { printf >&2 %s\\n "$0: failed to create temp files"; return 1; }

    ret=0 tail="${STFU_TAIL:-20}"
    "$@" >| "$out" 2>| "$err" || ret=$?
    if [ $ret != 0 ]; then
        printf 'command failed with exit status %s:\n' $ret >&2
        echo2 "$@"
        echo2
        note '$ tail -n' "$tail" "$out"
        tail -n "$tail" "$out" >&2
        echo2
        note '$ tail -n' "$tail" "$err"
        tail -n "$tail" "$err" >&2
    fi
    return $ret
}

${preload+:} . ~/sh/bootstrap
