#!/usr/bin/env sh
# compat: +ash +bash +dash +hush -ksh +mksh -oksh +osh +posh +yash +zsh

__subdue() { ### @subdue
    ### reconfigure your terminal's color scheme using a preset for [recolor.](#recolor)
    ###
    ### ![subdue colors](https://eaguru.guru/t/subdue.png)
    __recolor_install

    # since we're already wrapped in a subshell,
    # override recolor to avoid extra subshells.
    recolor() { __recolor "$@"; }

    ForegroundColour '#ECECEC'
    BackgroundColour '#111111'
        CursorColour '#F9F9F9'

               Black '#111111'
                 Red '#B62A1F'
               Green '#41B43C'
                Blue '#1D52E1'
              Yellow '#ED9433'
                Cyan '#40ADAC'
             Magenta '#BA3CB9'
               White '#BDBDBD'

           BoldBlack '#747474'
             BoldRed '#F43E31'
           BoldGreen '#4FEB49'
            BoldBlue '#4391F9'
          BoldYellow '#F4F415'
            BoldCyan '#3AF5F4'
         BoldMagenta '#E84EE6'
           BoldWhite '#ECECEC'
}

subdue()(__subdue "$@")
[ -n "${preload+-}" ] || . ~/sh/preload || exit 2
eval ${preload:-preload} recolor
[ -n "${preload+-}" ] || __subdue "$@"
