#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

sum() { ### @-
    ### compute the summation of its arguments without forking processes.
    ### this relies on the shell's built-in arithmetic operators.
    ###
    ### ```
    ### $ sum 1 2 3
    ### 6
    ### ```
    ###
    ### **TODO:** consider renaming because sum(1) already exists.
    local sum=0
    for i; do
        i="${i%,}"
        : $((sum+=i))
    done
    echo "$sum"
}

[ -n "${preload+-}" ] || sum "$@"
