#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

tpad() {
    for f; do
        gm convert -bordercolor "#000000FF" -border 1x1 "$f" "${f%.png}.tt.png"
    done
}

[ "${SOURCING:-0}" -gt 0 ] || tpad "$@"
