#!/usr/bin/env bash
# YES_ZSH

tpad() {
    while [ $# -gt 0 ]; do
        gm convert -bordercolor "#000000FF" -border 1x1 "$1" "${1/.png/}.tt.png";
        shift
    done
}

[ "${SOURCING:-0}" -gt 0 ] || tpad "$@"
