#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH

trash() { ### @-
    ### output a given number of bytes from `/dev/random`.
    ###
    ### ```
    ### $ trash 10 | xxp
    ### 3A A5 4F C7 6D 89 E7 D7 F7 0C
    ### ```
    [ $# -le 1 ] || { printf "%s\n" "$0: too many arguments" >&2; return 1; }
    dd status=none if=/dev/random bs=1 count="${1:?missing count argument}"
}

[ -n "${preload+-}" ] || trash "$@"
