#!/usr/bin/env sh
# compat: +ash +bash +dash +hush +ksh +mksh +oksh +osh +posh +yash +zsh

unwrap() { ### @- join paragraphs into one line each.
    awk 'BEGIN{RS="\n\n";FS="\n"}{for(i=1;i<=NF;i++)printf "%s ",$i;print "\n"}'
}

[ -n "${preload+-}" ] || unwrap "$@"
