#!/usr/bin/env sh
# YES_ZSH
# YES_BASH
# YES_DASH
# YES_ASH

unwrap() { ### @- join paragraphs into one line each.
    awk '\''BEGIN{RS="\n\n";FS="\n"}{for(i=1;i<=NF;i++)printf "%s ",$i;print "\n"}'\'
}

[ -n "${preload+-}" ] || unwrap "$@"
