--blank-lines-after-procedures
--braces-on-if-line
--cuddle-else
--case-indentation 0
--format-first-column-comments
--declaration-indentation 0
--indent-level 8
--continue-at-parentheses
--line-length 79
--no-blank-lines-after-commas
--no-comment-delimiters-on-blank-lines
--dont-left-justify-declarations
--dont-format-first-column-comments
--no-space-after-function-call-names
--procnames-start-lines
--start-left-side-of-comments
--swallow-optional-blank-lines
